// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpfsjrirnlshgadovxzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwZnNqcmlybmxzaGdhZG92eHpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDQzOTIsImV4cCI6MjA3MzI4MDM5Mn0.fmc09J2lL7_kcCJC8zEqj8ReAiPO-rCh1CFXEfJpPG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});